src/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

src/seci/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^timeseries/', include('timeseries.urls', namespace='timeseries')),
    url(r'^', include('main.urls', namespace='main')),
]

src/timeseries/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^generate/$', views.generate_data, name='generate_data'),
]

src/timeseries/models.py
import datetime
import calendar

from collections import defaultdict

from django.db import models


class Location(models.Model):
    REGION = 1
    CITY = 2
    TARGET_TYPE_CHOICES = (
        (REGION, 'Region'),
        (CITY, 'City'),
    )

    AMAZONAS = 1
    ANCASH = 2
    APURIMAC = 3
    AREQUIPA = 4
    REGION_CODE_CHOICES = (
        (AMAZONAS, 'Amazonas'),
        (ANCASH, 'Ancash'),
        (APURIMAC, 'Apurimac'),
        (AREQUIPA, 'Arequipa'),
    )

    # name = models.CharField(max_length=200)
    canonical_name = models.CharField(max_length=200)
    # parent = models.ForeignKey('Location', null=True, blank=True)
    # target_type = models.IntegerField(default=REGION, choices=TARGET_TYPE_CHOICES)
    # region_code = models.IntegerField(default=AREQUIPA, choices=REGION_CODE_CHOICES)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.canonical_name


    def get_month_formatted_data(self, start_year, start_month, end_year, end_month):
        response = {
            'labels': [],
            'datasets': {},
        }

        # Fill labels
        for year in range(start_year, end_year+1):
            start_month_loop = 1
            if start_year == year:
                start_month_loop = start_month

            for month in range(start_month_loop, 13):
                if month > end_month and year==end_year:
                    break
                response['labels'].append(calendar.month_name[month] + ' ' + str(year))

        # Fill dataset
        data = MonthAggregationData.objects.filter(
            location=self,
            year__gte=start_year, year__lte=end_year
            ).order_by('year', 'month')

        for item in data:
            response['datasets'].setdefault(item.get_event_type_display(), []).append(
                item.events,
            )
        return response



class MonthAggregationData(models.Model):
    VIOLENT_CRIME = 1
    MURDER = 2
    FORCIBLE_RAPE = 3
    ROBBERY = 4
    AGGRAVATED_ASSAULT = 5
    PROPERTY_CRIME = 6
    BURGLARY = 7
    LARCENY_THEFT = 8
    MOTOR_VEHICLE_THEFT = 9
    ARSON = 10

    EVENT_TYPE_CHOICES = (
        (VIOLENT_CRIME, 'Violent crime'),
        (MURDER, 'Murder'),
        (FORCIBLE_RAPE, 'Forcible rape'),
        (ROBBERY, 'Robbery'),
    )
    '''
        (AGGRAVATED_ASSAULT, 'Aggravated assault'),
        (PROPERTY_CRIME, 'Property crime'),
        (BURGLARY, 'Burglary'),
        (LARCENY_THEFT, 'Larcent theft'),
        (MOTOR_VEHICLE_THEFT, 'Motor vehicle theft'),
        (ARSON, 'Arson'),
    )
    '''


    YEAR_CHOICES = []
    for year in range(1980, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((year, year))

    MONTH_CHOICES = []
    for month in range(1, 13):
        MONTH_CHOICES.append((month, calendar.month_name[month]))

    year = models.IntegerField(choices=YEAR_CHOICES)
    month = models.IntegerField(choices=MONTH_CHOICES)
    event_type = models.IntegerField(choices=EVENT_TYPE_CHOICES)
    events = models.IntegerField(default=0)
    location = models.ForeignKey(Location)

src/main/views.py
from django.shortcuts import render, get_object_or_404

from timeseries.models import Location


def home(request):
    context = {}

    location_list = Location.objects.all()

    location_id = request.GET.get('location')
    if location_id:
        # Dates are inclusive
        start_year = 2015
        start_month = 1

        end_year = 2015
        end_month = 5

        location = get_object_or_404(Location, id=location_id)
        context['location'] = location
        context['data'] = location.get_month_formatted_data(start_year, start_month, end_year, end_month)

    context['location_list'] = location_list

    return render(request, 'main/home.html', context)

src/timeseries/views.py
import random

from django.http import HttpResponse
from django.shortcuts import render

from .models import Location, MonthAggregationData

def generate_data(request):
    MonthAggregationData.objects.all().delete()

    # Dates are inclusive
    start_year = 2015
    start_month = 1

    end_year = 2015
    end_month = 5

    '''
    def generate_for_location(parent_location, year, month, event_type, left):
        # Retrieve all children
        location_children_list = Location.objects.filter(parent=parent_location)

        total = left
        total_left = total

        for location in location_children_list:
            # Split average and a random based on left
            random_variation = (total/len(location_children_list))//10
            location_events = total//len(location_children_list) + random.randint(random_variation*-1, random_variation)
            total_left -= location_events
            if total_left < 0:
                location_events = total_left
                total_left = 0

            month_aggregation, _ = MonthAggregationData.objects.get_or_create(
                year=year,
                month=month,
                location=location,
                event_type=event_type,
                )
            month_aggregation.events = location_events
            month_aggregation.save()

            generate_for_location(location, year, month, event_type, location_events)
    '''

    # Retrieve all locations
    # location_list = Location.objects.filter(parent__isnull=True)
    location_list = Location.objects.all()

    for location in location_list:
        for event_type, event_name in MonthAggregationData.EVENT_TYPE_CHOICES:
            # First set an initial random event number
            events = random.randint(1000, 10000)
            for year in range(start_year, end_year+1):
                start_month_loop = 1
                if start_year == year:
                    start_month_loop = start_month

                for month in range(start_month_loop, 13):
                    if month > end_month and year==end_year:
                        break

                    random_variation = events//random.randint(3, 12)
                    events = events + random.randint(random_variation*-1, random_variation)
                    if events < 0:
                        events += random_variation*2

                    month_aggregation, _ = MonthAggregationData.objects.get_or_create(
                        year=year,
                        month=month,
                        location=location,
                        event_type=event_type,
                        )
                    month_aggregation.events=events
                    month_aggregation.save()
                    # generate_for_location(location, year, month, event_type, events)

    return HttpResponse('Generated')

src/main/templates/main/base.html
{% load static %}

<html>
  <head>
    <title></title>
    <link href='http://fonts.googleapis.com/css?family=Lato:200,300,400,600,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}" media="screen" />
    </head>
  <body>
    {% block header %}
    {% endblock %}

    <section class="main" role="main">
      {% block content %}
      {% endblock %}
    </section>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'main/js/script.js' %}"></script>
    <script src="{% static 'main/js/chart.min.js' %}"></script>
    {% block footer_scripts %}{% endblock %}
  </body>
</html>

src/main/templates/main/home-2.html
{% extends 'main/base.html' %}

{% block header %}
<div class="map">
  <div id="map-canvas" style="height:300px;"></div>
</div>
{% endblock %}

{% block content %}



<div class="search-bar">
    <input type="search" placeholder="Buscar ubicación" id="pac-input"/>
    <button type="submit">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png"
     alt="Search Icon">
  </button>
</div>

<div class="search-results">
  <canvas id="time-series"></canvas>
</div>


<p class="text-center">
  <br />
  <br />
  <br />
  <a href="{% url 'timeseries:generate_data' %}">Generate random data</a>
</p>

{% endblock %}




{% block footer_scripts %}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
<script src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/src/markerclusterer.js"></script>
<script>
// This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.

function initialize() {

  var markers = [];
  var map = new google.maps.Map(document.getElementById('map-canvas'), {
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var defaultBounds = new google.maps.LatLngBounds(
      new google.maps.LatLng(-33.8902, 151.1759),
      new google.maps.LatLng(-33.8474, 151.2631));
  map.fitBounds(defaultBounds);

  // Create the search box and link it to the UI element.
  var input = /** @type {HTMLInputElement} */(
      document.getElementById('pac-input'));

  var searchBox = new google.maps.places.SearchBox(
    /** @type {HTMLInputElement} */(input));

  // Listen for the event fired when the user selects an item from the
  // pick list. Retrieve the matching places for that item.
  google.maps.event.addListener(searchBox, 'places_changed', function() {
    var places = searchBox.getPlaces();

    if (places.length == 0) {
      return;
    }
    for (var i = 0, marker; marker = markers[i]; i++) {
      marker.setMap(null);
    }

    // For each place, get the icon, place name, and location.
    markers = [];
    var bounds = new google.maps.LatLngBounds();
    for (var i = 0, place; place = places[i]; i++) {
      var image = {
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(25, 25)
      };

      // Create a marker for each place.
      var marker = new google.maps.Marker({
        map: map,
        icon: image,
        title: place.name,
        position: place.geometry.location
      });

      markers.push(marker);

      bounds.extend(place.geometry.location);
    }

    map.fitBounds(bounds);
  });

  // Bias the SearchBox results towards places that are within the bounds of the
  // current map's viewport.
  google.maps.event.addListener(map, 'bounds_changed', function() {
    var bounds = map.getBounds();
    searchBox.setBounds(bounds);
  });
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>


<script>
var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My First dataset",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: [65, 59, 80, 81, 56, 55, 40]
        },
        {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: [28, 48, 40, 19, 86, 27, 90]
        }
    ]
};


var ctx = document.getElementById("time-series").getContext("2d");
var myLineChart = new Chart(ctx).Line(data);

</script>

{% endblock %}

src/main/templates/main/home.html
{% extends 'main/base.html' %}

{% load main_extras %}


{% block header %}
<div class="map">
  <div id="map-canvas" style="height:300px;"></div>
</div>
{% endblock %}

{% block content %}
<div class="text-center give-me-space">
  <div class="dropdown">
    <div class="dropdown-container">
      <p class="dropdown-description">Región</p>
      <p class="dropdown-button">{% if location %}{{ location }}{% else %}Seleccionar{% endif %}</p>
      <ul class="dropdown-menu dropdown-select">
        {% for location in location_list %}
        <li onclick="goToLocationWith({{ location.id }})">{{ location }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

<div class="search-results">
  <canvas id="time-series"></canvas>
</div>
<p class="text-center">
  <div id="time-series-legend"></div>
</p>

<p class="text-center">
  <br />
  <br />
  <br />
  <a href="{% url 'timeseries:generate_data' %}">Generate random data</a>
</p>



<p>
  {{ data  }}
</p>

{% endblock %}




{% block footer_scripts %}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
<script src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/src/markerclusterer.js"></script>
<script>
// This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.

function initialize() {

  var markers = [];

  var mapOptions = {
    zoom: 11,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
  };

  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);


  var defaultBounds = new google.maps.LatLngBounds(
    {% if location %}
      new google.maps.LatLng({{ location.latitude}} + 0.01, {{ location.longitude }} + 0.01),
      new google.maps.LatLng({{ location.latitude}} - 0.01, {{ location.longitude }} - 0.01)
    {% else %}
      new google.maps.LatLng(-11.766071, -76.836120),
      new google.maps.LatLng(-11.776071, -76.846120),
      new google.maps.LatLng(-11.756071, -76.826120)
    {% endif %}
    );
  map.fitBounds(defaultBounds);

  // Create the search box and link it to the UI element.
  var input = /** @type {HTMLInputElement} */(
      document.getElementById('pac-input'));

  var searchBox = new google.maps.places.SearchBox(
    /** @type {HTMLInputElement} */(input));

  // Listen for the event fired when the user selects an item from the
  // pick list. Retrieve the matching places for that item.
  google.maps.event.addListener(searchBox, 'places_changed', function() {
    var places = searchBox.getPlaces();

    if (places.length == 0) {
      return;
    }
    for (var i = 0, marker; marker = markers[i]; i++) {
      marker.setMap(null);
    }

    // For each place, get the icon, place name, and location.
    markers = [];
    var bounds = new google.maps.LatLngBounds();
    for (var i = 0, place; place = places[i]; i++) {
      var image = {
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(25, 25)
      };

      // Create a marker for each place.
      var marker = new google.maps.Marker({
        map: map,
        icon: image,
        title: place.name,
        position: place.geometry.location
      });

      markers.push(marker);

      bounds.extend(place.geometry.location);
    }

    map.fitBounds(bounds);
  });

  // Add marker
  {% if location %}
  var myLatlng = new google.maps.LatLng({{ location.latitude }}, {{ location.longitude }});
  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Hello World!'
  });
  var bounds = new google.maps.LatLngBounds();
  bounds.extend(marker.getPosition());
  bounds.extend(new google.maps.LatLng({{ location.latitude }} + 0.01, {{ location.longitude }} + 0.01));
  bounds.extend(new google.maps.LatLng({{ location.latitude }} - 0.01, {{ location.longitude }} - 0.01));
  map.fitBounds(bounds);
  {% endif %}

  // Bias the SearchBox results towards places that are within the bounds of the
  // current map's viewport.
  google.maps.event.addListener(map, 'bounds_changed', function() {
    var bounds = map.getBounds();
    searchBox.setBounds(bounds);
  });
}

google.maps.event.addDomListener(window, 'load', initialize);


</script>

{# AQUI EMPIEZA LA SERIE #}


<script>
var rgb_colors = [
        "22, 160, 133",
        "39, 174, 96",
        "41, 128, 185",
        "142, 68, 173",
        "44, 62, 80",
        "243, 156, 18",
        "211, 84, 0",
        "192, 57, 43",
        "189, 195, 199",
        "127, 140, 141",
        "26, 188, 156",
        "46, 204, 113",
        "52, 152, 219",
        "155, 89, 182",
        "52, 73, 94",
        "241, 196, 15",
        "230, 126, 34",
        "231, 76, 60",
        "236, 240, 241",
        "149, 165, 166",
    ]

var data = {
    labels: [
      {% for label in data.labels %}
      "{{ label }}",
      {% endfor %}
    ],
    datasets: [
        {% for dataset_name, dataset in data.datasets.items %}
        {
            label: "{{ dataset_name }}",
            fillColor: "rgba(" + rgb_colors[{{ forloop.counter0 }}] + ",0.2)",
            strokeColor: "rgba(" + rgb_colors[{{ forloop.counter0 }}] + ",1)",
            pointColor: "rgba(" + rgb_colors[{{ forloop.counter0 }}] + ",1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(" + rgb_colors[{{ forloop.counter0 }}] + ",1)",
            data: [
            {% for value in dataset %}
            {{ value }},
            {% endfor %}
            ]
        },
        {% endfor %}
      ]
};

var data_backup = data['datasets'].slice();

var ctx = document.getElementById("time-series").getContext("2d");
{% verbatim %}
var myLineChart = new Chart(ctx).Line(data, {
  legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\">&nbsp;</span><a val=\"<%=i%>\" class=\"dataset-legend-item\"><%if(datasets[i].label){%><%=datasets[i].label%><%}%></a></li><%}%></ul>"
});
{% endverbatim %}


function goToLocationWith(locationId){
    window.location.href = '?location=' + locationId;
}
$('#time-series-legend').html(myLineChart.generateLegend());
{% comment %}
console.debug(myLineChart.generateLegend());


$(document).ready(function(){
  $(".dataset-legend-item").click(function() {
    id = parseInt($(this).attr('val'));
    console.debug(myLineChart.datasets[id]);
    if(myLineChart.datasets[id].points.length > 0) {
      myLineChart.datasets[id].points = [];
    } else {
      console.debug(data_backup[id]['data']);
      console.debug(data_backup[id]['label']);
    }
    myLineChart.addData(data_backup[id]['data'], data_backup[id]['label']);
    console.debug(myLineChart.datasets[id]);
    myLineChart.update();
  });
});
{% endcomment %}



</script>

{% endblock %}